[project]
name = "assigment-1-dua-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm-handler>=0.1.4",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
